[package]
authors = ["Caleb Quilley <cquilley@tylercapital.co.uk>"]
name = "qsm"
version = "2.1.0"

[dependencies]
chrono = "*"
libc = "0.2.29"

[profile]

[profile.release]
lto = true
rustflags = ["-C", "target-cpu=native"]

[features]
debug = []